services:
  - type: web_service
    name: rrmotors-frontend
    buildCommand: npm install && npx vite build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: VITE_API_URL
        value: https://rrmotors.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
